### PR TITLE
Extensive modifications to Latin set

### PR DESCRIPTION
**Pull request by aaronbell**
Hi Coji,

Over the last couple of days I've made a significant number of changes to MPLUS_1, MPLUS_2, and MPLUS_Code. However, it appears that you have continued to work on the files since I last pulled from this repository and I don't know what changes you've made. 

Can you review the updated files for any issues and merge any changes that you've made in the last 4-5 days into my files? 

Additionally this PR includes an updated version of the Kanji set that will is master compatible. My next step will be to create the build script that will assemble everything together. 

Thanks,
Aaron

Full Latin set changelist:

MPlus 1 & 2

- G is super wide. Narrowed to be more like the C. Lowered crossbar as well. 
- slightly shifted top of S to the right to make it more stable
- Changed structure of ẞ to follow more conventional shape
- reduced length of top of /a
- adjusted anchor on jdotless
- rounded top of ß a bit. 
- angled up the 1
- adjusted round top of 2
- shifted top stroke of 3 to the left
- tweaked bottom dot of ?
- gave period-han a little more rounding
- changed ₫ model
- followed change to G in ₲
- corrected ₼ shape
- major overhaul of diacritics, especially for vietnamese.
	- ogonek needs to keep inside the right side of the character
	- general alignments improved
	- horn shape tweaked
	- updated components in iogonek

MPlus Code
- slightly shifted top of S to the right to make it more stable
- Changed structure of ẞ to follow more conventional shape
- tweaked /a top
- rounded bottom of ð
- adjusted anchor on /r
- shifted top of /s
- rounded top of /ß
- position of slash on ł
- adjusted anchor on jdotless
- minor rounding to top of 2
- shifted top stroke of 3 to the left
- shifted bottom of ?
- updated 60 variants of many currency symbols to be 600 (was 500)
- - corrected ₼ shape
- major overhaul of diacritics, especially for vietnamese.
	- ogonek needs to keep inside the right side of the character
	- general alignments improved
	- horn shape tweaked
	- updated components in iogonek
- fixed widths of characters that didn't align with 500 / 600 standard. emdash, quotedbl, bulletoperator, divisionslash, brokenbar, daggerdbl

### CODE REVIEW

**Comment by coz-m** [comment]
Hi Aaron,

Thank you for the huge amount of correction work. I am very grateful for the glyphs fix that I am not familiar with.
However, let me readjust the design modifications for "S", "G", "a", "s", "1".

Especially the position and length of the "G" crossbar, which is certainly the design of the Gill Sans and Futura fonts, but I've always thought that the center of gravity was too low. Is the position of my "G" crossbar so unnatural for native English speakers?

And why are there 8 Instances in MPLUS-Kanji.glyphs?

Best regards,
Coji

**Comment by aaronbell** [comment]
If I recall, the crossbar of the G was placed at the same level as the H and was long, which made it feel quite high to me. I normally see it slightly lower:
Screen Shot 2021-04-29 at 6 09 28 AM

The 8 instances in MPLUS-Kanji were based on the 8 instances that you had with overlaps corrected in your original source files. If you don't need that many instances, we can certainly cut some. Would make my job easier! :) Do you just want the lightest, the middle, and the boldest?

Cheers
Aaron

**Comment by coz-m** [comment]
HI Aaron,

For the time being, I first tried to modify "SGa1₲" of MPLus 1 again.

- The great Adrian Frutiger also lifts the "G" crossbar in the Avenir font after the Frutiger font, and I'd be grateful if you could accept this amendment.

Screen Shot 2021-04-30 at 10 14 03

- If the length of top of "a" is too short, it will give a comical impression, so I tried to modify it to the extent that it balances.

- I'm sorry. I don't know why it was 8 instances, but since it was deployed with 7 weights from the beginning, the ExtraLight instance of MPLUS-Kanji.glyphs is unnecessary.

Thanks,
Coji

**Comment by aaronbell** [comment]
Hi Coji,

Sounds good! Whatever you think is best. My modifications are just suggestions—it is your design and you can make it how you would like!

Cheers,
Aaron

**Comment by coz-m** [comment]
Thank you for your very generous words!

**Pull request merged**
