### PR TITLE
Finalizing build process

### PR DESCRIPTION
**Pull request by aaronbell**
The build process has been generally finalized for the Mplus font families. At current, 33 fonts (!) are being made automatically:

Mplus 1 - variable font & 7 static instances
Mplus 2 - variable font & 7 static instances
Mplus Code - variable font & 5 static instances
Mplus Latin - variable font & 10 static instances

I made some minor modifications to the fonts where I caught issues or to update metadata but otherwise kept the sources as is. 

If you find any issues, or have any other concerns, please let me know!

### CODE REVIEW

**Comment by aaronbell** [comment]
@mintoming Just updating you :)

**Comment by aaronbell** [comment]
Thanks. I'll correct the names. 

I wasn't able to repro the Mplus1 and Mplus2 bugs in Illustrator. No idea what would be causing those.

The bug in Mplus Latin is odd. I think it is Illustrator related as well, but I can resolve it by removing the overlaps in the corner.

**Comment by coz-m** [comment]
> Thanks. I'll correct the names.

I'm sorry for granting my selfishness.

> I wasn't able to repro the Mplus1 and Mplus2 bugs in Illustrator. No idea what would be causing those.

Roger that. It's a mysterious phenomenon.

>The bug in Mplus Latin is odd. I think it is Illustrator related as well, but I can resolve it by removing the overlaps in the corner.

- Thank you for solving it. I have tweaked the design of the "m" 50/60 Thin glyph. please confirm.

- It seems that the "bracket layer" is not working with the Kana characters of Mplus 1 Code.

https://user-images.githubusercontent.com/55127265/117790327-36380400-b284-11eb-82b6-65579bd74de9.mov

Correct behavior with Mplus 1.

https://user-images.githubusercontent.com/55127265/117790552-6e3f4700-b284-11eb-82f2-7bac5bfa2586.mov

- Is it possible to change the name displayed in the font list from "Mplus1 Code" to "Mplus 1 Code"?
fontnames

- Is it possible to set the display name of Mplus Code Latin in the font weight list to be like "Thin 50", "Thin 60", "Light 50", "Light 60"?
weights

I'm sorry for the detailed request, but please consider it.

**Comment by coz-m** [comment]
Thank you for responding to my many requests. I regret the bug of displaying variable fonts in Illustrator, but I am very happy that you made them variable fonts including kanji glyphs. I'm still incredibly surprised.

Please take the work to the next stage. And finally, please also create a OTF.

**Comment by aaronbell** [comment]
Thank you! 

BTW, I happened to try out Mplus 1 on my laptop that has an older version of Illustrator installed (23.0.1) and was able to repro the bug. However, after upgrading to the latest version of Illustrator (25.2.3), the bug disappeared. 

As such, I believe that this bug is definitely related to Illustrator.

**Comment by coz-m** [comment]
Thank you for your confirmation. I also confirmed that the bug was fixed by upgrading from 24.0.1 to 25.2.3. I was relieved :-)

**Pull request merged**
